# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake

# The command to remove a file.
RM = /home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chenyidong/CudaOT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chenyidong/CudaOT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/spack/spack/opt/spack/linux-debian12-zen2/gcc-11.3.0/cmake-3.26.3-gytjv5owjrxi7wdi3sjxvvcqf3nn26js/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenyidong/CudaOT/CMakeFiles /home/chenyidong/CudaOT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenyidong/CudaOT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Multiscale

# Build rule for target.
Multiscale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Multiscale
.PHONY : Multiscale

# fast build rule for target.
Multiscale/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Multiscale.dir/build.make CMakeFiles/Multiscale.dir/build
.PHONY : Multiscale/fast

#=============================================================================
# Target rules for targets named FastEMD

# Build rule for target.
FastEMD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FastEMD
.PHONY : FastEMD

# fast build rule for target.
FastEMD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastEMD.dir/build.make CMakeFiles/FastEMD.dir/build
.PHONY : FastEMD/fast

#=============================================================================
# Target rules for targets named SparseSK

# Build rule for target.
SparseSK: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SparseSK
.PHONY : SparseSK

# fast build rule for target.
SparseSK/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SparseSK.dir/build.make CMakeFiles/SparseSK.dir/build
.PHONY : SparseSK/fast

#=============================================================================
# Target rules for targets named LogDomainSK

# Build rule for target.
LogDomainSK: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LogDomainSK
.PHONY : LogDomainSK

# fast build rule for target.
LogDomainSK/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogDomainSK.dir/build.make CMakeFiles/LogDomainSK.dir/build
.PHONY : LogDomainSK/fast

#=============================================================================
# Target rules for targets named Common

# Build rule for target.
Common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Common
.PHONY : Common

# fast build rule for target.
Common/fast:
	$(MAKE) $(MAKESILENT) -f Common/CMakeFiles/Common.dir/build.make Common/CMakeFiles/Common.dir/build
.PHONY : Common/fast

#=============================================================================
# Target rules for targets named Models

# Build rule for target.
Models: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Models
.PHONY : Models

# fast build rule for target.
Models/fast:
	$(MAKE) $(MAKESILENT) -f Common/Models/CMakeFiles/Models.dir/build.make Common/Models/CMakeFiles/Models.dir/build
.PHONY : Models/fast

#=============================================================================
# Target rules for targets named Sinkhorn

# Build rule for target.
Sinkhorn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Sinkhorn
.PHONY : Sinkhorn

# fast build rule for target.
Sinkhorn/fast:
	$(MAKE) $(MAKESILENT) -f Sinkhorn/CMakeFiles/Sinkhorn.dir/build.make Sinkhorn/CMakeFiles/Sinkhorn.dir/build
.PHONY : Sinkhorn/fast

#=============================================================================
# Target rules for targets named ShortCutSolver

# Build rule for target.
ShortCutSolver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ShortCutSolver
.PHONY : ShortCutSolver

# fast build rule for target.
ShortCutSolver/fast:
	$(MAKE) $(MAKESILENT) -f ShortCutSolver/CMakeFiles/ShortCutSolver.dir/build.make ShortCutSolver/CMakeFiles/ShortCutSolver.dir/build
.PHONY : ShortCutSolver/fast

#=============================================================================
# Target rules for targets named SparseSinkhorn

# Build rule for target.
SparseSinkhorn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SparseSinkhorn
.PHONY : SparseSinkhorn

# fast build rule for target.
SparseSinkhorn/fast:
	$(MAKE) $(MAKESILENT) -f SparseSinkhorn/CMakeFiles/SparseSinkhorn.dir/build.make SparseSinkhorn/CMakeFiles/SparseSinkhorn.dir/build
.PHONY : SparseSinkhorn/fast

#=============================================================================
# Target rules for targets named LogSinkhorn

# Build rule for target.
LogSinkhorn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LogSinkhorn
.PHONY : LogSinkhorn

# fast build rule for target.
LogSinkhorn/fast:
	$(MAKE) $(MAKESILENT) -f LogSinkhorn/CMakeFiles/LogSinkhorn.dir/build.make LogSinkhorn/CMakeFiles/LogSinkhorn.dir/build
.PHONY : LogSinkhorn/fast

FastEMD.o: FastEMD.cpp.o
.PHONY : FastEMD.o

# target to build an object file
FastEMD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastEMD.dir/build.make CMakeFiles/FastEMD.dir/FastEMD.cpp.o
.PHONY : FastEMD.cpp.o

FastEMD.i: FastEMD.cpp.i
.PHONY : FastEMD.i

# target to preprocess a source file
FastEMD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastEMD.dir/build.make CMakeFiles/FastEMD.dir/FastEMD.cpp.i
.PHONY : FastEMD.cpp.i

FastEMD.s: FastEMD.cpp.s
.PHONY : FastEMD.s

# target to generate assembly for a file
FastEMD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FastEMD.dir/build.make CMakeFiles/FastEMD.dir/FastEMD.cpp.s
.PHONY : FastEMD.cpp.s

LogDomainSK.o: LogDomainSK.cpp.o
.PHONY : LogDomainSK.o

# target to build an object file
LogDomainSK.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogDomainSK.dir/build.make CMakeFiles/LogDomainSK.dir/LogDomainSK.cpp.o
.PHONY : LogDomainSK.cpp.o

LogDomainSK.i: LogDomainSK.cpp.i
.PHONY : LogDomainSK.i

# target to preprocess a source file
LogDomainSK.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogDomainSK.dir/build.make CMakeFiles/LogDomainSK.dir/LogDomainSK.cpp.i
.PHONY : LogDomainSK.cpp.i

LogDomainSK.s: LogDomainSK.cpp.s
.PHONY : LogDomainSK.s

# target to generate assembly for a file
LogDomainSK.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogDomainSK.dir/build.make CMakeFiles/LogDomainSK.dir/LogDomainSK.cpp.s
.PHONY : LogDomainSK.cpp.s

Multiscale.o: Multiscale.cpp.o
.PHONY : Multiscale.o

# target to build an object file
Multiscale.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Multiscale.dir/build.make CMakeFiles/Multiscale.dir/Multiscale.cpp.o
.PHONY : Multiscale.cpp.o

Multiscale.i: Multiscale.cpp.i
.PHONY : Multiscale.i

# target to preprocess a source file
Multiscale.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Multiscale.dir/build.make CMakeFiles/Multiscale.dir/Multiscale.cpp.i
.PHONY : Multiscale.cpp.i

Multiscale.s: Multiscale.cpp.s
.PHONY : Multiscale.s

# target to generate assembly for a file
Multiscale.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Multiscale.dir/build.make CMakeFiles/Multiscale.dir/Multiscale.cpp.s
.PHONY : Multiscale.cpp.s

SparseSK.o: SparseSK.cpp.o
.PHONY : SparseSK.o

# target to build an object file
SparseSK.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SparseSK.dir/build.make CMakeFiles/SparseSK.dir/SparseSK.cpp.o
.PHONY : SparseSK.cpp.o

SparseSK.i: SparseSK.cpp.i
.PHONY : SparseSK.i

# target to preprocess a source file
SparseSK.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SparseSK.dir/build.make CMakeFiles/SparseSK.dir/SparseSK.cpp.i
.PHONY : SparseSK.cpp.i

SparseSK.s: SparseSK.cpp.s
.PHONY : SparseSK.s

# target to generate assembly for a file
SparseSK.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SparseSK.dir/build.make CMakeFiles/SparseSK.dir/SparseSK.cpp.s
.PHONY : SparseSK.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Common"
	@echo "... FastEMD"
	@echo "... LogDomainSK"
	@echo "... LogSinkhorn"
	@echo "... Models"
	@echo "... Multiscale"
	@echo "... ShortCutSolver"
	@echo "... Sinkhorn"
	@echo "... SparseSK"
	@echo "... SparseSinkhorn"
	@echo "... FastEMD.o"
	@echo "... FastEMD.i"
	@echo "... FastEMD.s"
	@echo "... LogDomainSK.o"
	@echo "... LogDomainSK.i"
	@echo "... LogDomainSK.s"
	@echo "... Multiscale.o"
	@echo "... Multiscale.i"
	@echo "... Multiscale.s"
	@echo "... SparseSK.o"
	@echo "... SparseSK.i"
	@echo "... SparseSK.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

